//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoMayaAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AprendiendoMayaEntities : DbContext
    {
        public AprendiendoMayaEntities()
            : base("name=AprendiendoMayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Nivele> Niveles { get; set; }
        public virtual DbSet<Palabra> Palabras { get; set; }
        public virtual DbSet<Puntuacione> Puntuaciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
