//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoMayaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        public int ID_Palabra { get; set; }
        public string PalabraMaya { get; set; }
        public string PalabraEspanol { get; set; }
        public string PalabraIngles { get; set; }
        public string Imagen { get; set; }
        public string Audio { get; set; }
        public Nullable<bool> PalabraNueva { get; set; }
        public string Categoria { get; set; }
    }
}
